// Generated by the math-sdk port (stake_engine/void_chronos) via `generate_configs()`.
// Do not hand-edit `configFe.json` -- re-run `python3 games/void_chronos/run.py` on the
// math-sdk side and copy library/configs/config_fe_void_chronos.json over it instead.
import raw from './configFe.json';

type RawSymbolDef = {
	paytable: { [count: string]: number }[] | null;
	special_properties?: string[];
};

const symbols: Record<string, { paytable?: { [count: string]: number }[]; special_properties?: string[] }> = {};
for (const entry of raw.symbols as Record<string, RawSymbolDef>[]) {
	const [name, def] = Object.entries(entry)[0];
	symbols[name] = def.paytable ? { paytable: def.paytable, special_properties: def.special_properties } : { special_properties: def.special_properties };
}

export default {
	providerName: raw.providerName,
	gameName: raw.gameName,
	gameID: raw.gameID,
	rtp: raw.rtp,
	numReels: raw.numReels,
	numRows: raw.numRows,
	betModes: raw.betModes,
	symbols,
	paddingReels: raw.paddingReels,
};
