// Real books generated by the math-sdk port (stake_engine/void_chronos), decompressed
// from library/publish_files/books_<mode>.jsonl.zst -- not hand-authored fixtures.
// Covers: a zero-win spin, a small win, a natural free-spin trigger, a Portal Wild
// conversion, and a Chronos Storm bonus buy with an Orb Collector event.
export default [
	{
		"id": 0,
		"payoutMultiplier": 0.0,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S5"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						},
						{
							"name": "S8"
						},
						{
							"name": "S8"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S3"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						},
						{
							"name": "W",
							"wild": true
						}
					]
				],
				"paddingPositions": [
					32,
					130,
					60,
					253,
					230
				],
				"gameType": "basegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 1,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 2,
				"type": "finalWin",
				"amount": 0
			}
		]
	},
	{
		"id": 6,
		"payoutMultiplier": 0.3,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S3"
						},
						{
							"name": "S6"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S2"
						},
						{
							"name": "S7"
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "S6"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S4"
						},
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						}
					]
				],
				"paddingPositions": [
					77,
					202,
					24,
					37,
					274
				],
				"gameType": "basegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 1,
				"type": "winInfo",
				"totalWin": 30,
				"wins": [
					{
						"symbol": "S4",
						"win": 30,
						"positions": [
							{
								"reel": 0,
								"row": 2
							},
							{
								"reel": 2,
								"row": 1
							},
							{
								"reel": 2,
								"row": 2
							},
							{
								"reel": 2,
								"row": 4
							},
							{
								"reel": 2,
								"row": 5
							},
							{
								"reel": 2,
								"row": 6
							},
							{
								"reel": 3,
								"row": 1
							},
							{
								"reel": 3,
								"row": 5
							},
							{
								"reel": 4,
								"row": 3
							},
							{
								"reel": 4,
								"row": 6
							}
						],
						"meta": {
							"globalMult": 1,
							"clusterMult": 1,
							"winWithoutMult": 28,
							"overlay": {
								"reel": 2,
								"row": 4
							}
						}
					}
				]
			},
			{
				"index": 2,
				"type": "updateTumbleWin",
				"amount": 30
			},
			{
				"index": 3,
				"type": "tumbleBoard",
				"newSymbols": [
					[
						{
							"name": "S8"
						}
					],
					[],
					[
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S8"
						},
						{
							"name": "S1"
						}
					]
				],
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 2
					},
					{
						"reel": 2,
						"row": 1
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 2,
						"row": 4
					},
					{
						"reel": 2,
						"row": 5
					},
					{
						"reel": 2,
						"row": 6
					},
					{
						"reel": 3,
						"row": 1
					},
					{
						"reel": 3,
						"row": 5
					},
					{
						"reel": 4,
						"row": 3
					},
					{
						"reel": 4,
						"row": 6
					}
				]
			},
			{
				"index": 4,
				"type": "setWin",
				"amount": 30,
				"winLevel": 2
			},
			{
				"index": 5,
				"type": "setTotalWin",
				"amount": 30
			},
			{
				"index": 6,
				"type": "finalWin",
				"amount": 30
			}
		]
	},
	{
		"id": 1596,
		"payoutMultiplier": 1.1,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S6"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S5"
						},
						{
							"name": "S5"
						},
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S8"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S4"
						},
						{
							"name": "S5"
						}
					]
				],
				"paddingPositions": [
					123,
					167,
					97,
					78,
					271
				],
				"gameType": "basegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					1
				]
			},
			{
				"index": 1,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 2,
				"type": "freeSpinTrigger",
				"totalFs": 10,
				"positions": [
					{
						"reel": 1,
						"row": 4
					},
					{
						"reel": 2,
						"row": 5
					},
					{
						"reel": 3,
						"row": 3
					},
					{
						"reel": 4,
						"row": 5
					}
				]
			},
			{
				"index": 3,
				"type": "updateFreeSpin",
				"amount": 0,
				"total": 10
			},
			{
				"index": 4,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						},
						{
							"name": "P",
							"portal": true
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S7"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S5"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						}
					]
				],
				"paddingPositions": [
					214,
					299,
					32,
					81,
					153
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 5,
				"type": "portalWildInfo",
				"conversions": [
					{
						"portal": {
							"reel": 0,
							"row": 2
						},
						"converted": [
							{
								"reel": 0,
								"row": 2
							},
							{
								"reel": 1,
								"row": 2
							},
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 0,
								"row": 3
							}
						]
					}
				]
			},
			{
				"index": 6,
				"type": "winInfo",
				"totalWin": 40,
				"wins": [
					{
						"symbol": "S3",
						"win": 20,
						"positions": [
							{
								"reel": 0,
								"row": 4
							},
							{
								"reel": 0,
								"row": 5
							},
							{
								"reel": 2,
								"row": 1
							},
							{
								"reel": 2,
								"row": 2
							},
							{
								"reel": 3,
								"row": 6
							},
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 0,
								"row": 2
							},
							{
								"reel": 0,
								"row": 3
							},
							{
								"reel": 1,
								"row": 2
							},
							{
								"reel": 1,
								"row": 4
							}
						],
						"meta": {
							"globalMult": 1,
							"clusterMult": 1,
							"winWithoutMult": 20,
							"overlay": {
								"reel": 1,
								"row": 4
							}
						}
					},
					{
						"symbol": "S1",
						"win": 20,
						"positions": [
							{
								"reel": 0,
								"row": 6
							},
							{
								"reel": 1,
								"row": 3
							},
							{
								"reel": 1,
								"row": 6
							},
							{
								"reel": 2,
								"row": 4
							},
							{
								"reel": 3,
								"row": 2
							},
							{
								"reel": 4,
								"row": 3
							},
							{
								"reel": 4,
								"row": 4
							},
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 0,
								"row": 2
							},
							{
								"reel": 0,
								"row": 3
							},
							{
								"reel": 1,
								"row": 2
							},
							{
								"reel": 1,
								"row": 4
							}
						],
						"meta": {
							"globalMult": 1,
							"clusterMult": 1,
							"winWithoutMult": 22,
							"overlay": {
								"reel": 1,
								"row": 3
							}
						}
					}
				]
			},
			{
				"index": 7,
				"type": "updateTumbleWin",
				"amount": 40
			},
			{
				"index": 8,
				"type": "tumbleBoard",
				"newSymbols": [
					[
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S8"
						},
						{
							"name": "S6"
						},
						{
							"name": "S8"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S8"
						}
					]
				],
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 4
					},
					{
						"reel": 0,
						"row": 5
					},
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 0,
						"row": 2
					},
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 0,
						"row": 6
					},
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 0,
						"row": 2
					},
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 1,
						"row": 2
					},
					{
						"reel": 1,
						"row": 4
					},
					{
						"reel": 1,
						"row": 3
					},
					{
						"reel": 1,
						"row": 6
					},
					{
						"reel": 1,
						"row": 2
					},
					{
						"reel": 1,
						"row": 4
					},
					{
						"reel": 2,
						"row": 1
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 2,
						"row": 4
					},
					{
						"reel": 3,
						"row": 6
					},
					{
						"reel": 3,
						"row": 2
					},
					{
						"reel": 4,
						"row": 3
					},
					{
						"reel": 4,
						"row": 4
					}
				]
			},
			{
				"index": 9,
				"type": "setWin",
				"amount": 40,
				"winLevel": 2
			},
			{
				"index": 10,
				"type": "setTotalWin",
				"amount": 40
			},
			{
				"index": 11,
				"type": "updateFreeSpin",
				"amount": 1,
				"total": 10
			},
			{
				"index": 12,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S8"
						},
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S2"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S7"
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S5"
						},
						{
							"name": "S5"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						}
					]
				],
				"paddingPositions": [
					264,
					46,
					50,
					90,
					98
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 13,
				"type": "winInfo",
				"totalWin": 10,
				"wins": [
					{
						"symbol": "S2",
						"win": 10,
						"positions": [
							{
								"reel": 0,
								"row": 1
							},
							{
								"reel": 0,
								"row": 3
							},
							{
								"reel": 1,
								"row": 5
							},
							{
								"reel": 1,
								"row": 6
							},
							{
								"reel": 2,
								"row": 3
							},
							{
								"reel": 3,
								"row": 2
							},
							{
								"reel": 4,
								"row": 2
							},
							{
								"reel": 4,
								"row": 3
							},
							{
								"reel": 4,
								"row": 5
							},
							{
								"reel": 2,
								"row": 2
							},
							{
								"reel": 2,
								"row": 4
							}
						],
						"meta": {
							"globalMult": 1,
							"clusterMult": 1,
							"winWithoutMult": 14,
							"overlay": {
								"reel": 2,
								"row": 4
							}
						}
					}
				]
			},
			{
				"index": 14,
				"type": "updateTumbleWin",
				"amount": 10
			},
			{
				"index": 15,
				"type": "tumbleBoard",
				"newSymbols": [
					[
						{
							"name": "S4"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S6"
						}
					]
				],
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 1
					},
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 1,
						"row": 5
					},
					{
						"reel": 1,
						"row": 6
					},
					{
						"reel": 2,
						"row": 3
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 2,
						"row": 4
					},
					{
						"reel": 3,
						"row": 2
					},
					{
						"reel": 4,
						"row": 2
					},
					{
						"reel": 4,
						"row": 3
					},
					{
						"reel": 4,
						"row": 5
					}
				]
			},
			{
				"index": 16,
				"type": "setWin",
				"amount": 10,
				"winLevel": 2
			},
			{
				"index": 17,
				"type": "setTotalWin",
				"amount": 50
			},
			{
				"index": 18,
				"type": "updateFreeSpin",
				"amount": 2,
				"total": 10
			},
			{
				"index": 19,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						},
						{
							"name": "S6"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 5
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						},
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S7"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S5"
						},
						{
							"name": "S7"
						},
						{
							"name": "S1"
						},
						{
							"name": "W",
							"wild": true
						}
					]
				],
				"paddingPositions": [
					53,
					279,
					183,
					68,
					193
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 20,
				"type": "setTotalWin",
				"amount": 50
			},
			{
				"index": 21,
				"type": "updateFreeSpin",
				"amount": 3,
				"total": 10
			},
			{
				"index": 22,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S5"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S7"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S5"
						},
						{
							"name": "P",
							"portal": true
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S7"
						},
						{
							"name": "S2"
						},
						{
							"name": "S7"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S7"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S2"
						}
					]
				],
				"paddingPositions": [
					282,
					64,
					262,
					151,
					243
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 23,
				"type": "setTotalWin",
				"amount": 50
			},
			{
				"index": 24,
				"type": "updateFreeSpin",
				"amount": 4,
				"total": 10
			},
			{
				"index": 25,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						},
						{
							"name": "S4"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S3"
						},
						{
							"name": "S6"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S7"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "S8"
						},
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						},
						{
							"name": "S2"
						}
					]
				],
				"paddingPositions": [
					182,
					259,
					258,
					221,
					137
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 26,
				"type": "setTotalWin",
				"amount": 50
			},
			{
				"index": 27,
				"type": "updateFreeSpin",
				"amount": 5,
				"total": 10
			},
			{
				"index": 28,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S3"
						},
						{
							"name": "S6"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S7"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "SC",
							"scatter": true
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S5"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S5"
						},
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S7"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						}
					]
				],
				"paddingPositions": [
					64,
					192,
					267,
					71,
					203
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 29,
				"type": "portalWildInfo",
				"conversions": [
					{
						"portal": {
							"reel": 1,
							"row": 5
						},
						"converted": [
							{
								"reel": 1,
								"row": 5
							},
							{
								"reel": 1,
								"row": 4
							},
							{
								"reel": 1,
								"row": 6
							}
						]
					},
					{
						"portal": {
							"reel": 2,
							"row": 2
						},
						"converted": [
							{
								"reel": 2,
								"row": 2
							},
							{
								"reel": 2,
								"row": 3
							}
						]
					}
				]
			},
			{
				"index": 30,
				"type": "winInfo",
				"totalWin": 60,
				"wins": [
					{
						"symbol": "S1",
						"win": 10,
						"positions": [
							{
								"reel": 0,
								"row": 3
							},
							{
								"reel": 1,
								"row": 2
							},
							{
								"reel": 1,
								"row": 3
							},
							{
								"reel": 2,
								"row": 4
							},
							{
								"reel": 3,
								"row": 5
							},
							{
								"reel": 4,
								"row": 3
							},
							{
								"reel": 1,
								"row": 4
							},
							{
								"reel": 1,
								"row": 5
							},
							{
								"reel": 1,
								"row": 6
							},
							{
								"reel": 2,
								"row": 2
							},
							{
								"reel": 2,
								"row": 3
							}
						],
						"meta": {
							"globalMult": 1,
							"clusterMult": 1,
							"winWithoutMult": 10,
							"overlay": {
								"reel": 2,
								"row": 4
							}
						}
					},
					{
						"symbol": "S5",
						"win": 50,
						"positions": [
							{
								"reel": 0,
								"row": 5
							},
							{
								"reel": 2,
								"row": 1
							},
							{
								"reel": 2,
								"row": 5
							},
							{
								"reel": 3,
								"row": 3
							},
							{
								"reel": 3,
								"row": 6
							},
							{
								"reel": 1,
								"row": 4
							},
							{
								"reel": 1,
								"row": 5
							},
							{
								"reel": 1,
								"row": 6
							},
							{
								"reel": 2,
								"row": 2
							},
							{
								"reel": 2,
								"row": 3
							}
						],
						"meta": {
							"globalMult": 1,
							"clusterMult": 1,
							"winWithoutMult": 50,
							"overlay": {
								"reel": 2,
								"row": 5
							}
						}
					}
				]
			},
			{
				"index": 31,
				"type": "updateTumbleWin",
				"amount": 60
			},
			{
				"index": 32,
				"type": "tumbleBoard",
				"newSymbols": [
					[
						{
							"name": "S8"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S7"
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S2"
						}
					]
				],
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 0,
						"row": 5
					},
					{
						"reel": 1,
						"row": 2
					},
					{
						"reel": 1,
						"row": 3
					},
					{
						"reel": 1,
						"row": 4
					},
					{
						"reel": 1,
						"row": 5
					},
					{
						"reel": 1,
						"row": 6
					},
					{
						"reel": 1,
						"row": 4
					},
					{
						"reel": 1,
						"row": 5
					},
					{
						"reel": 1,
						"row": 6
					},
					{
						"reel": 2,
						"row": 4
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 2,
						"row": 3
					},
					{
						"reel": 2,
						"row": 1
					},
					{
						"reel": 2,
						"row": 5
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 2,
						"row": 3
					},
					{
						"reel": 3,
						"row": 5
					},
					{
						"reel": 3,
						"row": 3
					},
					{
						"reel": 3,
						"row": 6
					},
					{
						"reel": 4,
						"row": 3
					}
				]
			},
			{
				"index": 33,
				"type": "setWin",
				"amount": 60,
				"winLevel": 2
			},
			{
				"index": 34,
				"type": "setTotalWin",
				"amount": 110
			},
			{
				"index": 35,
				"type": "updateFreeSpin",
				"amount": 6,
				"total": 10
			},
			{
				"index": 36,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S7"
						},
						{
							"name": "S4"
						},
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S7"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S7"
						},
						{
							"name": "S3"
						},
						{
							"name": "S6"
						},
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						},
						{
							"name": "S2"
						}
					]
				],
				"paddingPositions": [
					181,
					45,
					141,
					113,
					137
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 37,
				"type": "portalWildInfo",
				"conversions": [
					{
						"portal": {
							"reel": 3,
							"row": 6
						},
						"converted": [
							{
								"reel": 3,
								"row": 6
							},
							{
								"reel": 3,
								"row": 5
							},
							{
								"reel": 4,
								"row": 6
							},
							{
								"reel": 2,
								"row": 6
							}
						]
					}
				]
			},
			{
				"index": 38,
				"type": "setTotalWin",
				"amount": 110
			},
			{
				"index": 39,
				"type": "updateFreeSpin",
				"amount": 7,
				"total": 10
			},
			{
				"index": 40,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S4"
						},
						{
							"name": "S7"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S5"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "S4"
						},
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S7"
						},
						{
							"name": "S4"
						},
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S6"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S7"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S5"
						},
						{
							"name": "S7"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						}
					]
				],
				"paddingPositions": [
					157,
					166,
					140,
					21,
					23
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 41,
				"type": "setTotalWin",
				"amount": 110
			},
			{
				"index": 42,
				"type": "updateFreeSpin",
				"amount": 8,
				"total": 10
			},
			{
				"index": 43,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S5"
						},
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S8"
						},
						{
							"name": "S5"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S7"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "S5"
						},
						{
							"name": "S4"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S1"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S8"
						},
						{
							"name": "S3"
						},
						{
							"name": "S7"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						},
						{
							"name": "S2"
						},
						{
							"name": "P",
							"portal": true
						}
					]
				],
				"paddingPositions": [
					102,
					64,
					275,
					109,
					138
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 44,
				"type": "setTotalWin",
				"amount": 110
			},
			{
				"index": 45,
				"type": "updateFreeSpin",
				"amount": 9,
				"total": 10
			},
			{
				"index": 46,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "S7"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "S7"
						},
						{
							"name": "S8"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S6"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S7"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						}
					]
				],
				"paddingPositions": [
					10,
					83,
					22,
					21,
					121
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 47,
				"type": "setTotalWin",
				"amount": 110
			},
			{
				"index": 48,
				"type": "freeSpinEnd",
				"amount": 110,
				"winLevel": 2
			},
			{
				"index": 49,
				"type": "finalWin",
				"amount": 110
			}
		]
	},
	{
		"id": 2,
		"payoutMultiplier": 0.0,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S8"
						},
						{
							"name": "S8"
						},
						{
							"name": "S7"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S7"
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S6"
						},
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S8"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S6"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						}
					]
				],
				"paddingPositions": [
					278,
					66,
					189,
					242,
					297
				],
				"gameType": "basegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 1,
				"type": "portalWildInfo",
				"conversions": [
					{
						"portal": {
							"reel": 1,
							"row": 6
						},
						"converted": [
							{
								"reel": 1,
								"row": 6
							},
							{
								"reel": 2,
								"row": 6
							},
							{
								"reel": 1,
								"row": 5
							}
						]
					}
				]
			},
			{
				"index": 2,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 3,
				"type": "finalWin",
				"amount": 0
			}
		]
	},
	{
		"id": 219,
		"payoutMultiplier": 410.0,
		"events": [
			{
				"index": 0,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S5"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S7"
						},
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S8"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "SC",
							"scatter": true
						},
						{
							"name": "S6"
						},
						{
							"name": "S6"
						}
					],
					[
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						},
						{
							"name": "S8"
						},
						{
							"name": "S5"
						},
						{
							"name": "S2"
						}
					]
				],
				"paddingPositions": [
					21,
					257,
					226,
					243,
					99
				],
				"gameType": "basegame",
				"anticipation": [
					0,
					0,
					0,
					1,
					2
				]
			},
			{
				"index": 1,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 2,
				"type": "freeSpinTrigger",
				"totalFs": 12,
				"positions": [
					{
						"reel": 0,
						"row": 4
					},
					{
						"reel": 1,
						"row": 3
					},
					{
						"reel": 2,
						"row": 4
					},
					{
						"reel": 3,
						"row": 5
					}
				]
			},
			{
				"index": 3,
				"type": "updateFreeSpin",
				"amount": 0,
				"total": 12
			},
			{
				"index": 4,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "O",
							"multiplier": 2
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 100
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S7"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S2"
						}
					]
				],
				"paddingPositions": [
					39,
					105,
					30,
					270,
					157
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 5,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 6,
				"type": "updateFreeSpin",
				"amount": 1,
				"total": 12
			},
			{
				"index": 7,
				"type": "reveal",
				"board": [
					[
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S6"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S8"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S8"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						}
					]
				],
				"paddingPositions": [
					201,
					250,
					32,
					224,
					156
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 8,
				"type": "portalWildInfo",
				"conversions": [
					{
						"portal": {
							"reel": 1,
							"row": 1
						},
						"converted": [
							{
								"reel": 1,
								"row": 1
							},
							{
								"reel": 2,
								"row": 1
							}
						]
					}
				]
			},
			{
				"index": 9,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 10,
				"type": "updateFreeSpin",
				"amount": 2,
				"total": 12
			},
			{
				"index": 11,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S4"
						},
						{
							"name": "S7"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S5"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S6"
						},
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S7"
						},
						{
							"name": "S7"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "S7"
						},
						{
							"name": "S5"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S3"
						},
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						}
					]
				],
				"paddingPositions": [
					157,
					50,
					143,
					31,
					260
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 12,
				"type": "portalWildInfo",
				"conversions": [
					{
						"portal": {
							"reel": 4,
							"row": 5
						},
						"converted": [
							{
								"reel": 4,
								"row": 5
							},
							{
								"reel": 4,
								"row": 6
							}
						]
					}
				]
			},
			{
				"index": 13,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 14,
				"type": "updateFreeSpin",
				"amount": 3,
				"total": 12
			},
			{
				"index": 15,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S2"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S6"
						},
						{
							"name": "S3"
						},
						{
							"name": "S7"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 100
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S7"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S6"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S3"
						}
					]
				],
				"paddingPositions": [
					183,
					50,
					26,
					212,
					245
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 16,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 17,
				"type": "updateFreeSpin",
				"amount": 4,
				"total": 12
			},
			{
				"index": 18,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "S5"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "S6"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S7"
						},
						{
							"name": "S4"
						},
						{
							"name": "S5"
						},
						{
							"name": "O",
							"multiplier": 100
						},
						{
							"name": "S4"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						}
					]
				],
				"paddingPositions": [
					175,
					181,
					237,
					235,
					116
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 19,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 20,
				"type": "updateFreeSpin",
				"amount": 5,
				"total": 12
			},
			{
				"index": 21,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S1"
						},
						{
							"name": "O",
							"multiplier": 100
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "W",
							"wild": true
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S7"
						},
						{
							"name": "S4"
						},
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S8"
						},
						{
							"name": "O",
							"multiplier": 100
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S8"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S7"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						}
					]
				],
				"paddingPositions": [
					165,
					124,
					239,
					185,
					121
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 22,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 23,
				"type": "updateFreeSpin",
				"amount": 6,
				"total": 12
			},
			{
				"index": 24,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S4"
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "P",
							"portal": true
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "O",
							"multiplier": 100
						},
						{
							"name": "S3"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S5"
						},
						{
							"name": "S7"
						},
						{
							"name": "S1"
						},
						{
							"name": "S7"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S7"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S6"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S6"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S1"
						},
						{
							"name": "S7"
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						},
						{
							"name": "S2"
						},
						{
							"name": "S5"
						}
					]
				],
				"paddingPositions": [
					166,
					190,
					134,
					279,
					216
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 25,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 26,
				"type": "updateFreeSpin",
				"amount": 7,
				"total": 12
			},
			{
				"index": 27,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S7"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S4"
						},
						{
							"name": "S6"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						}
					],
					[
						{
							"name": "S7"
						},
						{
							"name": "S1"
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S5"
						},
						{
							"name": "O",
							"multiplier": 100
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S7"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S8"
						},
						{
							"name": "S7"
						},
						{
							"name": "S7"
						},
						{
							"name": "S3"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "P",
							"portal": true
						}
					]
				],
				"paddingPositions": [
					117,
					168,
					189,
					289,
					3
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 28,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 29,
				"type": "updateFreeSpin",
				"amount": 8,
				"total": 12
			},
			{
				"index": 30,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S5"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S8"
						},
						{
							"name": "S6"
						},
						{
							"name": "S8"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S5"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S1"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S6"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S7"
						},
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S8"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						}
					]
				],
				"paddingPositions": [
					233,
					295,
					126,
					179,
					136
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 31,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 32,
				"type": "updateFreeSpin",
				"amount": 9,
				"total": 12
			},
			{
				"index": 33,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S5"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S5"
						},
						{
							"name": "S7"
						},
						{
							"name": "S4"
						},
						{
							"name": "S5"
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S1"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S2"
						},
						{
							"name": "S1"
						},
						{
							"name": "O",
							"multiplier": 100
						},
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						}
					]
				],
				"paddingPositions": [
					75,
					171,
					235,
					136,
					260
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 34,
				"type": "portalWildInfo",
				"conversions": [
					{
						"portal": {
							"reel": 4,
							"row": 5
						},
						"converted": [
							{
								"reel": 4,
								"row": 5
							},
							{
								"reel": 3,
								"row": 5
							}
						]
					}
				]
			},
			{
				"index": 35,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 36,
				"type": "updateFreeSpin",
				"amount": 10,
				"total": 12
			},
			{
				"index": 37,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S3"
						},
						{
							"name": "S6"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S5"
						},
						{
							"name": "S3"
						},
						{
							"name": "SC",
							"scatter": true
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S4"
						},
						{
							"name": "S5"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "S6"
						}
					],
					[
						{
							"name": "S8"
						},
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S3"
						},
						{
							"name": "O",
							"multiplier": 50
						},
						{
							"name": "S6"
						},
						{
							"name": "S8"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S1"
						},
						{
							"name": "S6"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "S7"
						},
						{
							"name": "S1"
						},
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						},
						{
							"name": "S8"
						},
						{
							"name": "S2"
						}
					]
				],
				"paddingPositions": [
					64,
					202,
					31,
					3,
					197
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 38,
				"type": "setTotalWin",
				"amount": 0
			},
			{
				"index": 39,
				"type": "updateFreeSpin",
				"amount": 11,
				"total": 12
			},
			{
				"index": 40,
				"type": "reveal",
				"board": [
					[
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "C",
							"collector": true
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S4"
						},
						{
							"name": "O",
							"multiplier": 500
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "O",
							"multiplier": 1000
						},
						{
							"name": "S1"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S5"
						},
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S8"
						},
						{
							"name": "S1"
						},
						{
							"name": "S5"
						},
						{
							"name": "S6"
						},
						{
							"name": "S7"
						},
						{
							"name": "SC",
							"scatter": true
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S2"
						},
						{
							"name": "S8"
						},
						{
							"name": "S3"
						},
						{
							"name": "S7"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S2"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "P",
							"portal": true
						},
						{
							"name": "S1"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						},
						{
							"name": "S3"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						}
					]
				],
				"paddingPositions": [
					240,
					204,
					268,
					108,
					108
				],
				"gameType": "freegame",
				"anticipation": [
					0,
					0,
					0,
					0,
					0
				]
			},
			{
				"index": 41,
				"type": "portalWildInfo",
				"conversions": [
					{
						"portal": {
							"reel": 2,
							"row": 1
						},
						"converted": [
							{
								"reel": 2,
								"row": 1
							},
							{
								"reel": 2,
								"row": 2
							},
							{
								"reel": 3,
								"row": 1
							}
						]
					},
					{
						"portal": {
							"reel": 4,
							"row": 1
						},
						"converted": [
							{
								"reel": 4,
								"row": 1
							},
							{
								"reel": 4,
								"row": 2
							}
						]
					}
				]
			},
			{
				"index": 42,
				"type": "updateGlobalMult",
				"globalMult": 2050
			},
			{
				"index": 43,
				"type": "orbCollectorInfo",
				"orbPositions": [
					{
						"reel": 0,
						"row": 6
					},
					{
						"reel": 1,
						"row": 1
					},
					{
						"reel": 1,
						"row": 5
					}
				],
				"orbValues": [
					500,
					500,
					1000
				],
				"collectorPositions": [
					{
						"reel": 0,
						"row": 5
					}
				],
				"collectedTotal": 2000,
				"globalMultiplier": 2050
			},
			{
				"index": 44,
				"type": "winInfo",
				"totalWin": 41000,
				"wins": [
					{
						"symbol": "S3",
						"win": 41000,
						"positions": [
							{
								"reel": 0,
								"row": 2
							},
							{
								"reel": 0,
								"row": 3
							},
							{
								"reel": 0,
								"row": 4
							},
							{
								"reel": 3,
								"row": 3
							},
							{
								"reel": 4,
								"row": 5
							},
							{
								"reel": 4,
								"row": 6
							},
							{
								"reel": 2,
								"row": 1
							},
							{
								"reel": 2,
								"row": 2
							},
							{
								"reel": 3,
								"row": 1
							},
							{
								"reel": 4,
								"row": 1
							},
							{
								"reel": 4,
								"row": 2
							}
						],
						"meta": {
							"globalMult": 2050,
							"clusterMult": 1,
							"winWithoutMult": 20,
							"overlay": {
								"reel": 3,
								"row": 3
							}
						}
					}
				]
			},
			{
				"index": 45,
				"type": "updateTumbleWin",
				"amount": 41000
			},
			{
				"index": 46,
				"type": "tumbleBoard",
				"newSymbols": [
					[
						{
							"name": "W",
							"wild": true
						},
						{
							"name": "S5"
						},
						{
							"name": "S8"
						},
						{
							"name": "S3"
						},
						{
							"name": "S8"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S3"
						}
					],
					[
						{
							"name": "S2"
						},
						{
							"name": "S4"
						}
					],
					[
						{
							"name": "S7"
						},
						{
							"name": "S6"
						}
					],
					[
						{
							"name": "S8"
						},
						{
							"name": "S2"
						},
						{
							"name": "S4"
						},
						{
							"name": "S1"
						}
					]
				],
				"explodingSymbols": [
					{
						"reel": 0,
						"row": 2
					},
					{
						"reel": 0,
						"row": 3
					},
					{
						"reel": 0,
						"row": 4
					},
					{
						"reel": 2,
						"row": 1
					},
					{
						"reel": 2,
						"row": 2
					},
					{
						"reel": 3,
						"row": 3
					},
					{
						"reel": 3,
						"row": 1
					},
					{
						"reel": 4,
						"row": 5
					},
					{
						"reel": 4,
						"row": 6
					},
					{
						"reel": 4,
						"row": 1
					},
					{
						"reel": 4,
						"row": 2
					}
				]
			},
			{
				"index": 47,
				"type": "setWin",
				"amount": 41000,
				"winLevel": 9
			},
			{
				"index": 48,
				"type": "setTotalWin",
				"amount": 41000
			},
			{
				"index": 49,
				"type": "freeSpinEnd",
				"amount": 41000,
				"winLevel": 7
			},
			{
				"index": 50,
				"type": "finalWin",
				"amount": 41000
			}
		]
	}
];
